name: client_information_example
description: Demonstrates how to use the client_information plugin.

publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  client_information:
    path: ../

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  crypto: ^3.0.0-nullsafety
  http_parser: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0
  pedantic: ^1.10.0
  typed_data: ^1.3.0
  collection: ^1.15.0
  string_scanner: ^1.1.0
  source_span: ^1.8.0
  charcode: ^1.2.0
  term_glyph: ^1.2.0

flutter:
  uses-material-design: true
